name: Deploy website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  working-directory: ./website

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci

    - name: Build docusaurus
      run: npx docusaurus-write-translations

    - name: Setting whoaim
      run: |
        git config --global user.email "davesnx@users.noreply.github.com"
        git config --global user.name "Website Deployment CI"
        echo "machine github.com login davesnx password ${{ secrets.GH_TOKEN }}" > ~/.netrc

    - name: crowdin action
      uses: crowdin/github-action@1.5.2
      with:
        upload_translations: false
        download_translations: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

    - name: Deploy docusaurus
      run: GIT_USER="davesnx" USE_SSH=false npx docusaurus-publish
