# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci
      working-directory: ./website

    - name: Build docusaurus
      run: npx docusaurus-write-translations
      working-directory: ./website

    - name: Deploy docusaurus
      run: npx docusaurus-publish
      working-directory: ./website

    # - name: crowdin action
      # uses: crowdin/github-action@1.5.2
      # with:
        # upload_translations: false
        # download_translations: true
      # env:
        # GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        # CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        # CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

    # - name: Deploy website to GitHub Pages
      # working-directory: ./website
      # uses: JamesIves/github-pages-deploy-action@v4
